export const SAFE_PLACE_LABELS = {
  en: {
    title: "🧭 Find Safe Place",
    subtitle: "Real nearby infrastructure from OpenStreetMap — not an official NDMA/SDMA relief-centre list.",
    useLocation: "📍 Use My Location",
    locating: "Locating…",
    distance: "Distance",
    status: "Status",
    lastUpdated: "Last Updated",
    roadStatus: "Road Status",
    unavailable: "Data unavailable",
    getDirections: "Get Directions →",
    noResults: "No named nearby places found in OpenStreetMap for this location.",
    outsideNer: "Your location appears to be outside the NER monitoring region.",
    refresh: "↻ Refresh"
  },
  hi: {
    title: "🧭 सुरक्षित स्थान खोजें",
    subtitle: "OpenStreetMap से वास्तविक निकटवर्ती स्थान — यह आधिकारिक NDMA/SDMA राहत केंद्र सूची नहीं है।",
    useLocation: "📍 मेरा स्थान उपयोग करें",
    locating: "स्थान खोजा जा रहा है…",
    distance: "दूरी",
    status: "स्थिति",
    lastUpdated: "अंतिम अपडेट",
    roadStatus: "सड़क स्थिति",
    unavailable: "डेटा उपलब्ध नहीं है",
    getDirections: "रास्ता दिखाएं →",
    noResults: "इस स्थान के लिए OpenStreetMap में कोई नामित निकटवर्ती स्थान नहीं मिला।",
    outsideNer: "आपका स्थान NER निगरानी क्षेत्र के बाहर प्रतीत होता है।",
    refresh: "↻ ताज़ा करें"
  },
  bn: {
    title: "🧭 নিরাপদ স্থান খুঁজুন",
    subtitle: "OpenStreetMap থেকে প্রকৃত কাছাকাছি স্থান — এটি অফিসিয়াল NDMA/SDMA ত্রাণ কেন্দ্রের তালিকা নয়।",
    useLocation: "📍 আমার অবস্থান ব্যবহার করুন",
    locating: "অবস্থান খোঁজা হচ্ছে…",
    distance: "দূরত্ব",
    status: "অবস্থা",
    lastUpdated: "সর্বশেষ আপডেট",
    roadStatus: "রাস্তার অবস্থা",
    unavailable: "তথ্য উপলব্ধ নেই",
    getDirections: "দিকনির্দেশ দেখুন →",
    noResults: "এই অবস্থানের জন্য OpenStreetMap-এ কোনো নামযুক্ত কাছাকাছি স্থান পাওয়া যায়নি।",
    outsideNer: "আপনার অবস্থান NER পর্যবেক্ষণ অঞ্চলের বাইরে বলে মনে হচ্ছে।",
    refresh: "↻ রিফ্রেশ করুন"
  },
  as: {
    title: "🧭 সুৰক্ষিত ঠাই বিচাৰক",
    subtitle: "OpenStreetMap ৰ পৰা প্ৰকৃত ওচৰৰ ঠাই — এইটো আধিকাৰিক NDMA/SDMA সাহায্য কেন্দ্ৰৰ তালিকা নহয়।",
    useLocation: "📍 মোৰ অৱস্থান ব্যৱহাৰ কৰক",
    locating: "অৱস্থান বিচৰা হৈছে…",
    distance: "দূৰত্ব",
    status: "অৱস্থা",
    lastUpdated: "শেষ আপডেট",
    roadStatus: "ৰাস্তাৰ অৱস্থা",
    unavailable: "তথ্য উপলব্ধ নাই",
    getDirections: "দিশনিৰ্দেশ চাওক →",
    noResults: "এই অৱস্থানৰ বাবে OpenStreetMap ত কোনো নামাংকিত ওচৰৰ ঠাই পোৱা নগ'ল।",
    outsideNer: "আপোনাৰ অৱস্থান NER নিৰীক্ষণ অঞ্চলৰ বাহিৰত যেন লাগিছে।",
    refresh: "↻ ৰিফ্ৰেশ কৰক"
  },
  mni: {
    title: "🧭 Find Safe Place",
    subtitle: "OpenStreetMap na piba yathang leiba mapham — official NDMA/SDMA relief centre list natte.",
    useLocation: "📍 Use My Location",
    locating: "Locating…",
    distance: "Distance",
    status: "Status",
    lastUpdated: "Last Updated",
    roadStatus: "Road Status",
    unavailable: "Data unavailable",
    getDirections: "Get Directions →",
    noResults: "No named nearby places found.",
    outsideNer: "Your location appears to be outside the NER region.",
    refresh: "↻ Refresh"
  },
  kha: {
    title: "🧭 Find Safe Place",
    subtitle: "OpenStreetMap bad ki jaka lang — kane ka dei ki official NDMA/SDMA relief centre.",
    useLocation: "📍 Use My Location",
    locating: "Locating…",
    distance: "Distance",
    status: "Status",
    lastUpdated: "Last Updated",
    roadStatus: "Road Status",
    unavailable: "Data unavailable",
    getDirections: "Get Directions →",
    noResults: "No named nearby places found.",
    outsideNer: "Your location appears to be outside the NER region.",
    refresh: "↻ Refresh"
  },
  lus: {
    title: "🧭 Find Safe Place",
    subtitle: "OpenStreetMap-a mi hmun taktak — official NDMA/SDMA relief centre a ni lo.",
    useLocation: "📍 Use My Location",
    locating: "Locating…",
    distance: "Distance",
    status: "Status",
    lastUpdated: "Last Updated",
    roadStatus: "Road Status",
    unavailable: "Data unavailable",
    getDirections: "Get Directions →",
    noResults: "No named nearby places found.",
    outsideNer: "Your location appears to be outside the NER region.",
    refresh: "↻ Refresh"
  }
};

export const SAFE_PLACE_LANGUAGES = [
  { key: "en", label: "English" },
  { key: "hi", label: "Hindi (हिन्दी)" },
  { key: "bn", label: "Bengali (বাংলা)" },
  { key: "as", label: "Assamese (অসমীয়া)" },
  { key: "mni", label: "Manipuri / Meitei" },
  { key: "kha", label: "Khasi" },
  { key: "lus", label: "Mizo" }
];
